name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Setup Node.js 🔧
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install and Build 🔧
        run: |
          npm install
          npm run build -- --configuration production --base-href /mycelia/
          cp dist/mycelia/index.html dist/mycelia/404.html

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist/mycelia
          branch: gh-pages